### ISSUE TITLE
Astropy Issue

### ISSUE THREAD

**Issue by sjgunderson** [lucabaldini/ixpeobssim#736]
When attempting to use ixpeobssim commands, such xpselect, I get the following error message:

ImportError: cannot import name 'AnchoredEllipse' from 'mpl_toolkits.axes_grid1.anchored_artists'

Has there been changes to Astropy that are not compatible with the current version of ixpeobssim?

**Comment by lucabaldini** [comment]
Very possible.

Do you mind posting the output of 
```
[lbaldini@nblbaldini latex]$ python
Python 3.13.1 (main, Jan 10 2025, 09:58:06) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import astropy
>>> astropy.__version__
'7.0.1'
>>> 
```
? 

Thanks!
Luca

**Comment by sjgunderson** [comment]
>>> import astropy
>>> astropy.__version__
'6.1.4'
>>>

**Comment by lucabaldini** [comment]
Brief update (sorry it took me so long to get onto this, but teaching obligations are killing me).

I can confirm I trigger the same error with astropy 6.1.4, but everything seems to work fine with astropy 7.0.0 (and with an older astropy 5x, too).

I'd like to bisect the regression and understand which astropy versions are affected before I try and commit a patch. In the meantime, is there any way you can upgrade to astropy 7 to circumvent the issue?

**Comment by lucabaldini** [comment]
6.1.5 seems to work fine. 
6.1.3 has the same problem, and so does 6.1.2, 6.1.0. 

For some reason I was not able to install any older version of astropy on my system with Python 3.13. It might be necessary to use an older python for that.

**Comment by lucabaldini** [comment]
And, just for completeness, here is the full traceback:

```
[lbaldini@pcpi0188 ixpeobssim]$ xpselect.py 
Traceback (most recent call last):
  File "/home/users/lbaldini/work/ixpeobssim/ixpeobssim/bin/xpselect.py", line 27, in <module>
    from ixpeobssim.evt.subselect import xEventSelect
  File "/home/users/lbaldini/work/ixpeobssim/ixpeobssim/evt/subselect.py", line 27, in <module>
    from ixpeobssim.evt.event import xEventFile
  File "/home/users/lbaldini/work/ixpeobssim/ixpeobssim/evt/event.py", line 29, in <module>
    from ixpeobssim.core.fitsio import FITS_TO_NUMPY_TYPE_DICT, set_tlbounds
  File "/home/users/lbaldini/work/ixpeobssim/ixpeobssim/core/fitsio.py", line 30, in <module>
    from astropy.visualization.wcsaxes import WCSAxes
  File "/home/users/lbaldini/.pyenv/versions/3.13.1/lib/python3.13/site-packages/astropy/visualization/wcsaxes/__init__.py", line 19, in <module>
    from .helpers import *
  File "/home/users/lbaldini/.pyenv/versions/3.13.1/lib/python3.13/site-packages/astropy/visualization/wcsaxes/helpers.py", line 8, in <module>
    from mpl_toolkits.axes_grid1.anchored_artists import AnchoredEllipse, AnchoredSizeBar
ImportError: cannot import name 'AnchoredEllipse' from 'mpl_toolkits.axes_grid1.anchored_artists' (/home/users/lbaldini/.pyenv/versions/3.13.1/lib/python3.13/site-packages/mpl_toolkits/axes_grid1/anchored_artists.py)
```

**Comment by lucabaldini** [comment]
And this is the upstream commit in astropy fixing the issue 
https://github.com/astropy/astropy/commit/3fe7b259c02f4fe69306ddea04e308d448aa1401

The problem is an incompatibility with matplotlib 3.10. The pull request is at
https://github.com/astropy/astropy/pull/17144

**Comment by lucabaldini** [comment]
@sjgunderson It looks like this was catch by the astropy folks in the v7 series, and back-ported in astropy 6.1.5, so it is effectively only affecting a handful of astropy versions (probably 6.0.0 to 6.1.4, although I ). In addition, I am not sure how I would go about patching this downstream, as the error is triggered by a necessary import:

```
from astropy.visualization.wcsaxes import WCSAxes
``` 

I'd be tempted to close this as won't fix, but I was wondering if upgrading to astropy 6.1.5 is an option for you. 

Thanks!
Luca
