### ISSUE TITLE
Issue with skyfield.iokit.BytesIO

### ISSUE THREAD

**Issue by lucabaldini** [lucabaldini/ixpeobssim#302]
This manifested itself in our continuous integration for pull request #98  
[https://bitbucket.org/ixpesw/ixpeobssim/pull-requests/98](https://bitbucket.org/ixpesw/ixpeobssim/pull-requests/98)  
although it is totally unrelated to the changes in that branch. 

The error we are seeing in the CI log is

```
ixpeobssim/instrument/traj.py:36: in <module>
    from skyfield.iokit import parse_deltat_preds, parse_leap_seconds, BytesIO
E   ImportError: cannot import name 'BytesIO'
```

This seems to be working on my laptop with skyfield 1.20, while CircleCI uses skyfield 1.24

Original url: https://bitbucket.org/ixpesw/ixpeobssim/issues/302
Created on 2020-07-24T04:54:45.777017+00:00
